spring:
  application:
    name: spring-security
  datasource:
    url: jdbc:mysql://localhost:3306/demo?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
    username: meng
    password: password123